include(syndex.m4x)
include(int.m4x)
include(u.m4x)
processor_(U,u1,condition1,
SynDEx-6.5.2 (c)INRIA 2002, 13/1/2003 13:28:59
)


semaphores_(
  Semaphore_Thread_x,
  top_Condition_Out_c_o_c_o__u1_x_empty,
  top_Condition_Out_c_o_c_o__u1_x_full,
  top_c_div1_o_top_x_o_3_u1_x_empty,
  top_c_div1_o_top_x_o_3_u1_x_full,
  top_c_mod_o_top_x_o_2_u1_x_empty,
  top_c_mod_o_top_x_o_2_u1_x_full,
  top_c_Condition_In_i_c_i_o_top_x_o_4_u1_x_empty,
  top_c_Condition_In_i_c_i_o_top_x_o_4_u1_x_full,
  top_c_Condition_In_i_c_i_o_top_x_o_1_u1_x_empty,
  top_c_Condition_In_i_c_i_o_top_x_o_1_u1_x_full,
  top_x_o__u1_x_empty,
  top_x_o__u1_x_full,
)


alloc_(int,top_x_o,1)
alloc_(int,top_c_Condition_In_i_c_i_o,1)
alloc_(int,top_c_mod_o,1)
alloc_(int,top_c_div1_o,1)
alloc_(int,top_c_mul4_o,1)
alloc_(int,top_Condition_Out_c_o_c_o,1)

thread_(TCP,x,root,u1)
  loadFrom_(root)
  Pre0_(top_Condition_Out_c_o_c_o__u1_x_empty)
  loop_
    Suc1_(top_x_o__u1_x_empty)
    recv_(top_x_o,U,root,u1)
    Pre0_(top_x_o__u1_x_full)
    Suc1_(top_c_Condition_In_i_c_i_o_top_x_o_1_u1_x_empty)
    if_(top_x_o,1)
      recv_(top_c_Condition_In_i_c_i_o,U,root,u1)
    endif_
    Pre0_(top_c_Condition_In_i_c_i_o_top_x_o_1_u1_x_full)
    Suc1_(top_c_Condition_In_i_c_i_o_top_x_o_4_u1_x_empty)
    if_(top_x_o,4)
      recv_(top_c_Condition_In_i_c_i_o,U,root,u1)
    endif_
    Pre0_(top_c_Condition_In_i_c_i_o_top_x_o_4_u1_x_full)
    Suc1_(top_c_mod_o_top_x_o_2_u1_x_empty)
    if_(top_x_o,2)
      recv_(top_c_mod_o,U,root,u1)
    endif_
    Pre0_(top_c_mod_o_top_x_o_2_u1_x_full)
    Suc1_(top_c_div1_o_top_x_o_3_u1_x_empty)
    if_(top_x_o,3)
      recv_(top_c_div1_o,U,root,u1)
    endif_
    Pre0_(top_c_div1_o_top_x_o_3_u1_x_full)
    Suc1_(top_Condition_Out_c_o_c_o__u1_x_full)
    send_(top_Condition_Out_c_o_c_o,U,u1,root)
    Pre0_(top_Condition_Out_c_o_c_o__u1_x_empty)
  endloop_
  saveUpto_(root)
endthread_

main_
  spawn_thread_(x)
  int_Arit_mul(top_x_o,top_c_Condition_In_i_c_i_o,top_c_mul4_o)
  Pre1_(top_c_Condition_In_i_c_i_o_top_x_o_4_u1_x_empty,x)
  Pre1_(top_x_o__u1_x_empty,x)
  Pre1_(top_c_Condition_In_i_c_i_o_top_x_o_1_u1_x_empty,x)
  Pre1_(top_c_div1_o_top_x_o_3_u1_x_empty,x)
  Pre1_(top_c_mod_o_top_x_o_2_u1_x_empty,x)
  loop_
    Suc0_(top_c_Condition_In_i_c_i_o_top_x_o_4_u1_x_full,x)
    Suc0_(top_x_o__u1_x_full,x)
    if_(top_x_o,4)
      int_Arit_mul(top_x_o,top_c_Condition_In_i_c_i_o,top_c_mul4_o)
    endif_
    Pre1_(top_c_Condition_In_i_c_i_o_top_x_o_4_u1_x_empty,x)
    Suc0_(top_c_Condition_In_i_c_i_o_top_x_o_1_u1_x_full,x)
    Suc0_(top_c_div1_o_top_x_o_3_u1_x_full,x)
    Suc0_(top_c_mod_o_top_x_o_2_u1_x_full,x)
    Suc0_(top_Condition_Out_c_o_c_o__u1_x_empty,x)
    Implantation_Condition_Out(top_x_o,1,top_c_Condition_In_i_c_i_o,3,top_c_div1_o,2,top_c_mod_o,4,top_c_mul4_o,top_Condition_Out_c_o_c_o)
    Pre1_(top_c_Condition_In_i_c_i_o_top_x_o_1_u1_x_empty,x)
    Pre1_(top_c_div1_o_top_x_o_3_u1_x_empty,x)
    Pre1_(top_c_mod_o_top_x_o_2_u1_x_empty,x)
    Pre1_(top_x_o__u1_x_empty,x)
    Pre1_(top_Condition_Out_c_o_c_o__u1_x_full,x)
  endloop_
  int_Arit_mul(top_x_o,top_c_Condition_In_i_c_i_o,top_c_mul4_o)
  wait_endthread_(Semaphore_Thread_x)
endmain_

endprocessor_