# Contains config common to all docs
# For info specific to one doc, see Makefile.doc
XDVI = @xdvi
GV = @gv
LATEX = @latex
LATEX2HTML = @latex2html -noinfo -local_icons
HTML2TXT = ../../utils/html2text
BIBTEX = @bibtex
DVIPS = dvips
DVIPDF = dvipdf
PS2PDF = ps2pdf
FIG2EPS = @fig2dev -Leps

RM = rm -f
MV = mv -f
CP = cp -r
LN = ln -s
ECHO = @echo
MKDIR = mkdir -p
MORE = more
GTAR = tar

EXTERNALS_DIR = ../../externals/common/
